jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /estacionamiento
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/parqueaderoceiba
      username: miguel
      password: root
      hikari:
         poolName: pool
